site: ""
proxy: ""
whitelist-domain: ""
filter-length: ""
concurrent: 5
delay: 0
base: false
quiet: false
version: false
raw: false
depth: 1
no-redirect: false
output: ""
robots: true
blacklist: ""
timeout: 10
js: true
debug: false
