site: "https://www.fis.com.vn/"
sites: ""
proxy: ""
output: ""
user-agent: ""
cookie: ""
header: []
burp: ""
blacklist: ""
whitelist: ""
whitelist-domain: ""
filter-length: ""
threads: 1
concurrent: 5
depth: 4
delay: 0
random-delay: 0
timeout: 10
base: false
quiet: true
version: false
raw: false
no-redirect: false
robots: true
js: true
debug: false
verbose: false
other-source: false
length: false
include-subs: false
subs: false
include-other-source: false
sitemap: true
json: false