site: "https://fis.com.vn"
sites: ""
proxy: ""
output: ""
user-agent: ""
cookie: ""
header: []
burp: ""
blacklist: ""
whitelist: ""
whitelist-domain: ""
filter-length: ""
threads: 1
concurrent: 5
depth: 1
delay: 0
random-delay: 0
timeout: 10
base: false
quiet: false
version: false
raw: false
no-redirect: false
robots: true
js: true
debug: false
verbose: false
other-source: false
length: false
include-other-source: true
sitemap: false
json: false